version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "terragon-labs/maintainers"
    assignees:
      - "terragon-labs/security-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      security-updates:
        patterns:
          - "ring"
          - "rustls*"
          - "webpki*"
          - "x509*"
        update-types:
          - "security-update"
      tokio-ecosystem:
        patterns:
          - "tokio*"
          - "hyper*"
          - "tower*"
          - "axum*"
      wasm-tooling:
        patterns:
          - "wasm-*"
          - "js-sys"
          - "web-sys"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  # NPM dependencies (for tooling)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]