# Dependabot configuration for MCP WASM Edge Gateway
# Alternative to Renovate for dependency updates

version: 2

updates:
  # Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "admin-team"
    assignees:
      - "admin-team"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      rust-ecosystem:
        patterns:
          - "tokio*"
          - "serde*"
          - "tracing*"
          - "anyhow"
          - "thiserror"
      wasm-ecosystem:
        patterns:
          - "wasm-bindgen*"
          - "js-sys"
          - "web-sys"
          - "getrandom"
      security-libs:
        patterns:
          - "ring"
          - "rustls*"
          - "webpki*"

  # Node.js/npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "admin-team"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      semantic-release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "admin-team"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "admin-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Development container dependencies
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    reviewers:
      - "admin-team"
    labels:
      - "dependencies"
      - "devcontainer"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"