# Clippy configuration for MCP WASM Edge Gateway

# Enable extra lints for better code quality
avoid-breaking-exported-api = false
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 128

# Allow certain lints that may be too restrictive for our use case
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true

# Disable certain lints that may not be appropriate for embedded/WASM targets
warn-on-all-wildcard-imports = false