# Rustfmt configuration for MCP WASM Edge Gateway

# Edition
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Module"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80
doc_comment_code_block_width = 80

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
where_single_line = false
force_explicit_abi = true

# Functions and methods
fn_args_layout = "Tall"
fn_call_width = 60
fn_single_line = false
force_multiline_blocks = false

# Structs and enums
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
struct_lit_single_line = true

# Arrays and slices
array_width = 60
chain_width = 60

# Strings and formatting
format_strings = false
format_macro_matchers = false
format_macro_bodies = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false

# Spacing
spaces_around_ranges = false
type_punctuation_density = "Wide"
use_small_heuristics = "Default"

# Advanced options
merge_derives = true
reorder_impl_items = true
empty_item_single_line = true
overflow_delimited_expr = false
inline_attribute_width = 0

# Unstable features (when available)
# format_code_in_doc_comments = true
# wrap_matches = true
# short_array_element_width_threshold = 10