name: 🐛 Bug Report
description: Report a bug in MCP WASM Edge Gateway
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees:
  - terragon-labs/maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I can reproduce this bug consistently
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Gateway Core
        - Model Router
        - Security Module
        - Telemetry
        - WASM Runtime
        - Queue System
        - Docker Container
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System crash/data loss
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue/cosmetic
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Configure gateway with...
        2. Send request to...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13.0]
        - Gateway Version: [e.g., 0.1.0]
        - Rust Version: [e.g., 1.70.0]
        - Target Platform: [e.g., x86_64-unknown-linux-gnu]
        - Deployment: [e.g., Docker, native, WASM]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant logs, error messages, or stack traces
      placeholder: Paste logs here...
      render: text

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files (redact sensitive data)
      placeholder: |
        ```toml
        [gateway]
        bind_address = "0.0.0.0:8080"
        # ... other config
        ```
      render: toml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, related issues, potential causes...

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I'm willing to submit a PR to fix this bug
        - label: I can provide additional testing/feedback