name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - terragon-labs/maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!
        
        Before submitting, please check if a similar feature request already exists.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I have also considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Gateway
        - MCP Protocol
        - Security
        - Performance
        - Platform Support
        - Developer Experience
        - Documentation
        - Monitoring
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: Linux (x86_64)
        - label: Linux (aarch64)
        - label: Windows
        - label: macOS
        - label: Raspberry Pi
        - label: ESP32
        - label: Browser (WASM)
        - label: Mobile (iOS/Android)
        - label: All platforms

  - type: textarea
    id: use_case
    attributes:
      label: Use Case Description
      description: |
        Describe your specific use case and how this feature would help.
        Be as detailed as possible.
      placeholder: |
        In my project, I need to...
        This feature would help by...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: |
        What would need to be true for this feature to be considered complete?
        List specific, testable criteria.
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y scenario
        - [ ] Documentation is updated
        - [ ] Tests are included
    validations:
      required: false

  - type: dropdown
    id: breaking_change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to the API?
      options:
        - "No - Backward compatible"
        - "Yes - Breaking change required"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: implementation_ideas
    attributes:
      label: Implementation Ideas
      description: |
        Do you have any ideas about how this could be implemented?
        Technical details, API design, etc.
      placeholder: |
        This could be implemented by...
        API could look like...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide domain expertise

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided a clear problem statement
          required: true
        - label: I have described the proposed solution
          required: true
        - label: This feature aligns with the project goals
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature request here.
        Links to relevant resources, examples from other projects, etc.
      placeholder: Additional information...
    validations:
      required: false