name: ✨ Feature Request
description: Suggest a new feature for MCP WASM Edge Gateway
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - terragon-labs/maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your proposal.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the roadmap and this feature isn't already planned
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Performance Enhancement
        - New Platform Support
        - Security Improvement
        - Developer Experience
        - Model/AI Integration
        - Monitoring/Observability
        - Configuration/Setup
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High - Critical for adoption
        - Medium - Would significantly improve experience
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        - What should the feature do?
        - How should it work?
        - What would the API/interface look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions you've considered...

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a developer, I want to...
        2. When deploying to edge devices...
        3. For IoT applications...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the expected benefits?
      placeholder: |
        - Performance improvements
        - Reduced complexity
        - Better security
        - Wider platform support
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide code examples or mockups if applicable
      placeholder: |
        ```rust
        // Example usage
        let gateway = Gateway::new()
            .with_new_feature(config)
            .build()?;
        ```
      render: rust

  - type: textarea
    id: resources
    attributes:
      label: Related Resources
      description: Links to related issues, discussions, or external resources
      placeholder: |
        - Related issue: #123
        - Discussion: link
        - Documentation: link

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Technical considerations (check all that apply)
      options:
        - label: This feature requires breaking changes
        - label: This feature affects WASM compatibility
        - label: This feature impacts performance
        - label: This feature requires new dependencies
        - label: This feature needs documentation updates

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with design/specification
        - label: I can provide testing and feedback